name: $(date:yyyyMMdd)$(rev:.r)
pool:
  name: Azure Pipelines
variables:
  - group: certbot-variables
  - name: serviceConnection
    value: "KrakenfallAzureDnsAgent"
schedules:
- cron: "0 0 1 */2 *"
  displayName: string
  branches:
    include: 
    - main
  always: true
stages:
- stage: createCertStage
  displayName: 'Create Certificate and Upload to KV'
  jobs:
  - job: createCertPSJob
    displayName: 'PowerShell: Install Certbot, Create Certificate and Upload to KV'
    pool:
      vmImage: windows-2019
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens'
      inputs:
        rootDirectory: .cicd/certbot/azure
        targetFiles: '*'
        tokenPattern: rm
        enableTelemetry: false
      enabled: true
    - task: AzurePowerShell@5
      displayName: 'PowerShell: Install Certbot, Create Certificate and Upload to KV'
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptPath: '.cicd/certbot/azure/az-renew-cert.ps1'
        ScriptArguments:
          -email '$(DOMAIN_EMAIL)'
          -fqdn '$(CERTBOT_DOMAIN)'
          -keyVaultName '$(KEYVAULT_NAME)'
          -azDnsRgName '$(AZ_DNS_RG_NAME)'
          -txtName '$(TXT_NAME)'
          -PKPWD '$(PKPWD)'
        azurePowerShellVersion: LatestVersion
      enabled: true